-- Tabela de usuários (com self join para representar líderes e subordinados)
CREATE TABLE tbl_usuarios (
id_usuario NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 1 INCREMENT BY 1 PRIMARY KEY,
username VARCHAR2(100) NOT NULL UNIQUE,
password VARCHAR2(255) NOT NULL,
role_usuario VARCHAR2(100) NOT NULL,
funcao VARCHAR2(100) NOT NULL,
ativo NUMBER(1) DEFAULT 1 NOT NULL,
cargo VARCHAR2(100) NOT NULL,
setor VARCHAR2(100) NOT NULL,
id_lider NUMBER NULL,
CONSTRAINT fk_usuarios_lider FOREIGN KEY (id_lider) REFERENCES tbl_usuarios(id_usuario) ON DELETE SET NULL
);

-- Tabela de tipos de tarefa
CREATE TABLE tbl_tipo_tarefa (
id_tipo_tarefa NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 1 INCREMENT BY 1 PRIMARY KEY,
nome VARCHAR2(100) NOT NULL
);

-- Tabela de status da tarefa
CREATE TABLE tbl_status_tarefa (
id_status_tarefa NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 1 INCREMENT BY 1 PRIMARY KEY,
nome VARCHAR2(100) NOT NULL
);

CREATE TABLE tbl_tarefas (
id_tarefa NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 1 INCREMENT BY 1 PRIMARY KEY,
id_usuario NUMBER NOT NULL,
id_lider NUMBER NOT NULL,
id_tipo_tarefa NUMBER NOT NULL,
id_status_tarefa NUMBER NOT NULL,
descricao VARCHAR2(500),
tempo_estimado NUMBER(5,2),
tempo_real NUMBER(5,2),
data_inicio TIMESTAMP WITH TIME ZONE,
data_fim TIMESTAMP WITH TIME ZONE NULL,
CONSTRAINT fk_tarefas_usuario FOREIGN KEY (id_usuario)
REFERENCES tbl_usuarios(id_usuario),
CONSTRAINT fk_tarefas_lider FOREIGN KEY (id_lider)
REFERENCES tbl_usuarios(id_usuario),
CONSTRAINT fk_tarefas_tipo FOREIGN KEY (id_tipo_tarefa)
REFERENCES tbl_tipo_tarefa(id_tipo_tarefa),
CONSTRAINT fk_tarefas_status FOREIGN KEY (id_status_tarefa)
REFERENCES tbl_status_tarefa(id_status_tarefa)
);

-- Tabela de feedbacks (1:1 com tarefa)
CREATE TABLE tbl_feedbacks (
id_feedback NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 1 INCREMENT BY 1 PRIMARY KEY,
id_tarefa NUMBER UNIQUE NOT NULL,
conteudo CLOB NOT NULL,
data_gerado TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
CONSTRAINT fk_feedback_tarefa FOREIGN KEY (id_tarefa)
REFERENCES tbl_tarefas(id_tarefa)
ON DELETE CASCADE
);

